services:

    blitze.sitemaker.blocks.admin.controller:
        class: blitze\sitemaker\controller\blocks_admin
        arguments:
            - '@auth'
            - '@request'
            - '@user'
            - '@blitze.sitemaker.auto_lang'
            - '@blitze.sitemaker.blocks.action_handler'

    blitze.sitemaker.forum.controller:
        class: blitze\sitemaker\controller\forum
        arguments:
            - '@config'
            - '@controller.helper'
            - '@path_helper'
            - '@template'
            - '@user'

    blitze.sitemaker.menus.admin.controller:
        class: blitze\sitemaker\controller\menus_admin
        arguments:
            - '@request'
            - '@user'
            - '@blitze.sitemaker.menus.action_handler'
